/*
Assignment: Create a program that can try out every possible logical combination of the variables A, B, and C, 
and determine which combinations will yield a true statement. A few things to take note of, 
first there are eight different possible combinations of the three variables.
Make certain you test all eight of the combinations. The code itself will account for 50pts. 
Include the combinations of A, B, and C that cause the statement to be true for an additional 50pts.

(1)  (A and B) or (A and C)

(2) (A and C) and (B and !C)

(3) (A or B) and !(B or C)

(4) (A or (B and C)) and (!A and !B)

(5) ((B and C) or (C and A)) and (!(A or B) and C)

Please read each of the five carefully and make sure your code accurately reproduces the logical statement 
given for each problem. Note that the exclamation symbol indicates the logical “NOT” operator,
and the parentheses indicate which order the statements are to be performed in. 
Keep in mind since you’re testing all possible combinations of input for all five logical statements,
you’ll have forty answers generated by your program, in total.

*/
#include <iostream>
#include <array>

using namespace std;

int main()
{
    //Declare arrays of all possible inputs
    //There's probably a way to autogenerate these, but I'm betting we won't have another
    //lab like this for truth tables. (Watch me be wrong LOL)
    int A[8]={0,0,0,0,1,1,1,1};
    int B[8]={0,0,1,1,0,0,1,1};
    int C[8]={0,1,0,1,0,1,0,1};
    //The outputs will go here. Go team. 
    int outputArray1[8];
    int outputArray2[8];
    int outputArray3[8];
    int outputArray4[8];
    int outputArray5[8];
    // tell the user what the heck they are looking at
    cout << "The combinations are as follows:" << endl;
    for(int i = 0; i <8; i++){
        cout << endl << "Combination " << i+1 << " :"
        << " A: " << A[i]
        << " B: " << B[i]
        << " C: " << C[i];
    }
    
    cout << endl << "The output for each combination is provided in order, left to right" << endl;
    cout << "1 represents true, 0 represents false";
    cout << endl << "The output for question 1 is: ";
    for(int i = 0; i <8; i++){
        if ((A[i] and B[i]) or (A[i] and C[i])){
            outputArray1[i] = 1;
        }else
            outputArray1[i] = 0;
        cout << outputArray1[i] << " " ;
    }
    
        cout << endl << "The output for question 2 is: ";
    for(int i = 0; i <8; i++){
        if ((A[i] and C[i]) and (B[i] and (!C[i]))){
            outputArray2[i] = 1;
        }else
            outputArray2[i] = 0;
        cout << outputArray2[i] << " " ;
    }
    cout << endl << "The output for question 3 is: ";
    for(int i = 0; i <8; i++){
        if ((A[i] or B[i]) and (!(B[i] or C[i]))){
            outputArray2[i] = 1;
        }else
            outputArray2[i] = 0;
        cout << outputArray2[i] << " " ;
    }
    
    cout << endl << "The output for question 4 is: ";
    for(int i = 0; i <8; i++){
        if (( A[i] or (B[i] and C[i])) and (!A[i] and !B[i])){
            outputArray2[i] = 1;
        }else
            outputArray2[i] = 0;
        cout << outputArray2[i] << " " ;
    }
    
    cout << endl << "The output for question 5 is: ";
    for(int i = 0; i <8; i++){
        if (((B[i] and C[i]) or (C[i] and A[i])) and ( !(A[i] or B[i]) and C[i])){
            outputArray2[i] = 1;
        }else
            outputArray2[i] = 0;
        cout << outputArray2[i] << " " ;
    }
    
    

    
    

    return 0;
}